parameters:
#    tipddy_upv_form.example.class: Tipddy\UpvFormBundle\Example

services:
#    tipddy_upv_form.example:
#        class: %tipddy_upv_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
